package com.boatsafari.backend.service;

import com.boatsafari.backend.entity.Review;
import com.boatsafari.backend.repository.ReviewRepository;

import org.springframework.stereotype.Service;
import com.boatsafari.backend.repository.BookingRepository;
import com.boatsafari.backend.entity.Booking;
import com.boatsafari.backend.repository.TripScheduleRepository;
import com.boatsafari.backend.repository.UserRepository;
import com.boatsafari.backend.entity.User;

import java.util.List;
import java.time.LocalDateTime;
import java.util.Optional;

@Service
public class ReviewService {

        private final ReviewRepository reviewRepository;
        private final BookingRepository bookingRepository;
        private final TripScheduleRepository tripScheduleRepository;
        private final UserRepository userRepository;

        public ReviewService(
                        ReviewRepository reviewRepository,
                        BookingRepository bookingRepository,
                        TripScheduleRepository tripScheduleRepository,
                        UserRepository userRepository) {

                this.reviewRepository = reviewRepository;
                this.bookingRepository = bookingRepository;
                this.tripScheduleRepository = tripScheduleRepository;
                this.userRepository = userRepository;
        }
        // Create review

        public Review createReview(
                        Review review,
                        User authenticatedUser) {

                if (review.getRating() == null) {
                        throw new RuntimeException(
                                        "Rating is required");
                }

                if (review.getRating() < 1 ||
                                review.getRating() > 5) {

                        throw new RuntimeException(
                                        "Rating must be between 1 and 5");
                }

                if (review.getBooking() == null ||
                                review.getBooking().getId() == null) {

                        throw new RuntimeException(
                                        "Booking ID is required");
                }

                Booking booking = bookingRepository
                                .findById(review.getBooking().getId())
                                .orElseThrow(() -> new RuntimeException(
                                                "Booking not found"));

                // Customer can review only after the trip has finished
                LocalDateTime tripEndDateTime = LocalDateTime.of(
                                booking.getTripSchedule().getTripDate(),
                                booking.getTripSchedule().getEndTime());

                if (tripEndDateTime.isAfter(LocalDateTime.now())) {
                        throw new RuntimeException(
                                        "You can review this booking only after the trip is completed");
                }

                // Only CUSTOMER can create a review
                if (!"CUSTOMER".equalsIgnoreCase(
                                authenticatedUser.getRole())) {

                        throw new RuntimeException(
                                        "Customer access required");
                }

                // Customer can review only their own booking
                if (!booking.getCustomer()
                                .getId()
                                .equals(authenticatedUser.getId())) {

                        throw new RuntimeException(
                                        "You can only review your own booking");
                }

                if ("CANCELLED".equalsIgnoreCase(
                                booking.getStatus())) {

                        throw new RuntimeException(
                                        "Cannot review a cancelled booking");
                }

                if (reviewRepository.existsByBookingId(
                                booking.getId())) {

                        throw new RuntimeException(
                                        "A review already exists for this booking");
                }

                review.setBooking(booking);

                // Review date is generated by the backend
                review.setReviewDate(LocalDateTime.now());

                return reviewRepository.save(review);
        }

        // Get all reviews
        public List<Review> getAllReviews() {
                return reviewRepository.findAll();
        }

        // Get review by ID
        public Optional<Review> getReviewById(Long id) {
                return reviewRepository.findById(id);
        }

        // Get reviews by Trip Schedule ID
        public List<Review> getReviewsByTripScheduleId(
                        Long tripScheduleId) {

                if (!tripScheduleRepository.existsById(tripScheduleId)) {
                        throw new RuntimeException(
                                        "Trip schedule not found");
                }

                return reviewRepository
                                .findByBookingTripScheduleId(
                                                tripScheduleId);
        }

        // Get reviews by Customer ID
        public List<Review> getReviewsByCustomerId(
                        Long customerId) {

                User customer = userRepository.findById(customerId)
                                .orElseThrow(() -> new RuntimeException(
                                                "Customer not found"));

                if (!"CUSTOMER".equalsIgnoreCase(
                                customer.getRole())) {

                        throw new RuntimeException(
                                        "Selected user is not a CUSTOMER");
                }

                return reviewRepository
                                .findByBookingCustomerId(
                                                customerId);
        }

        public List<Review> getReviewsByCustomerForUser(
                        Long customerId,
                        User authenticatedUser) {

                User customer = userRepository.findById(customerId)
                                .orElseThrow(() -> new RuntimeException("Customer not found"));

                if (!"CUSTOMER".equalsIgnoreCase(
                                customer.getRole())) {

                        throw new RuntimeException(
                                        "Selected user is not a CUSTOMER");
                }

                // Manager can view any customer's reviews
                if ("MANAGER".equalsIgnoreCase(
                                authenticatedUser.getRole())) {

                        return reviewRepository
                                        .findByBookingCustomerId(customerId);
                }

                // Customer can view only their own review history
                if (customerId.equals(
                                authenticatedUser.getId())) {

                        return reviewRepository
                                        .findByBookingCustomerId(customerId);
                }

                throw new RuntimeException(
                                "You can only access your own review history");
        }

        // Get average rating by Trip Schedule ID
        public double getAverageRatingByTripScheduleId(
                        Long tripScheduleId) {

                if (!tripScheduleRepository.existsById(tripScheduleId)) {
                        throw new RuntimeException(
                                        "Trip schedule not found");
                }

                List<Review> reviews = reviewRepository
                                .findByBookingTripScheduleId(
                                                tripScheduleId);

                if (reviews.isEmpty()) {
                        return 0.0;
                }

                double total = 0;

                for (Review review : reviews) {
                        total += review.getRating();
                }

                return total / reviews.size();
        }

        // Update review
        public Review updateReview(
                        Long id,
                        Review updatedReview,
                        User authenticatedUser) {

                Review existingReview = reviewRepository.findById(id)
                                .orElseThrow(() -> new RuntimeException(
                                                "Review not found"));

                boolean isManager = "MANAGER".equalsIgnoreCase(
                                authenticatedUser.getRole());

                boolean isOwner = existingReview.getBooking()
                                .getCustomer()
                                .getId()
                                .equals(authenticatedUser.getId());

                if (!isManager && !isOwner) {
                        throw new RuntimeException(
                                        "You can only update your own reviews");
                }

                if (updatedReview.getRating() == null) {
                        throw new RuntimeException(
                                        "Rating is required");
                }

                if (updatedReview.getRating() < 1 ||
                                updatedReview.getRating() > 5) {

                        throw new RuntimeException(
                                        "Rating must be between 1 and 5");
                }

                existingReview.setRating(
                                updatedReview.getRating());

                existingReview.setComment(
                                updatedReview.getComment());

                return reviewRepository.save(
                                existingReview);
        }

        // Delete review
        public void deleteReview(
                        Long id,
                        User authenticatedUser) {

                Review review = reviewRepository
                                .findById(id)
                                .orElseThrow(() -> new RuntimeException(
                                                "Review not found"));

                boolean isManager = "MANAGER".equalsIgnoreCase(
                                authenticatedUser.getRole());

                boolean isOwner = review.getBooking()
                                .getCustomer()
                                .getId()
                                .equals(authenticatedUser.getId());

                if (!isManager && !isOwner) {
                        throw new RuntimeException(
                                        "You can only delete your own reviews");
                }

                reviewRepository.delete(review);
        }
}